# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testwindows.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(676, 449)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(530, 20, 91, 31))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(160, 80, 121, 61))
        self.pushButton2.setAutoDefault(False)
        self.pushButton2.setObjectName("pushButton2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(329, 160, 171, 31))
        self.label.setLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 190, 161, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 230, 60, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 250, 161, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setValidator(QtGui.QIntValidator(100000000,999999999))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action239r8y0u = QtWidgets.QAction(MainWindow)
        self.action239r8y0u.setObjectName("action239r8y0u")
        self.actioneciu = QtWidgets.QAction(MainWindow)
        self.actioneciu.setObjectName("actioneciu")
        self.actionkjcbkj4rbc = QtWidgets.QAction(MainWindow)
        self.actionkjcbkj4rbc.setObjectName("actionkjcbkj4rbc")
        self.actionckjr_b = QtWidgets.QAction(MainWindow)
        self.actionckjr_b.setObjectName("actionckjr_b")
        self.menu.addAction(self.action239r8y0u)
        self.menu.addAction(self.actioneciu)
        self.menu.addSeparator()
        self.menu.addAction(self.actionkjcbkj4rbc)
        self.menu.addSeparator()
        self.menu.addAction(self.actionckjr_b)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton1.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton1.setText(_translate("MainWindow", "关闭"))
        self.pushButton2.setText(_translate("MainWindow", "欢迎"))
        self.label.setText(_translate("MainWindow", "用户名"))
        self.label_2.setText(_translate("MainWindow", "密码"))
        self.menu.setTitle(_translate("MainWindow", "啊啊啊啊啊"))
        self.action239r8y0u.setText(_translate("MainWindow", "239r8y0u"))
        self.actioneciu.setText(_translate("MainWindow", "eciu"))
        self.actionkjcbkj4rbc.setText(_translate("MainWindow", "kjcbkj4rbc"))
        self.actionckjr_b.setText(_translate("MainWindow", "ckjr b"))
